# Generated by Django 4.0.2 on 2023-05-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_id_alter_blogauthor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='asd', unique=True),
            preserve_default=False,
        ),
    ]
