# Generated by Django 4.0.2 on 2023-05-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
    ]
